CREATE DATABASE CLIENTEDB;
GO

USE CLIENTEDB;
GO

CREATE TABLE CLIENTE (
IDCLIENTE INT PRIMARY KEY IDENTITY,
NOME VARCHAR(300) NOT NULL,
CPF VARCHAR(15) NOT NULL,
DATANASCIMENTO DATETIME NOT NULL,
GENERO CHAR(1) NOT NULL);
       
CREATE TABLE TELEFONE(
IDTELEFONE INT PRIMARY KEY IDENTITY,
IDCLIENTE INT NOT NULL,
DDD VARCHAR(5) NOT NULL,
NUMERO VARCHAR(10) NOT NULL,
CONSTRAINT FK_TEL_CLIENTE FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE));
GO          
